### ISSUE TITLE
Shared Properties

### ISSUE THREAD

**Issue by cyouh95** [zreska/prj-rev-bwfs-dasmoto#5]
Since all your `h2` elements have several shared properties, you could use that as your selector to style all of them at once. This will help reduce repetition in your code:

```css
h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

https://github.com/zreska/prj-rev-bwfs-dasmoto/blob/master/DasimotosArtsandCrafts/resources/css/index.css#L15-L37
